language: java
jdk:
  - openjdk8
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

script: './mvnw clean package'

before_deploy:
  - ls -al
  - zip -r codesquad-library *
  - zipinfo -m codesquad-library.zip
  - mkdir -p deploy
  - mv codesquad-library.zip deploy/codesquad-library.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: codesquad-library-backend
    region: ap-northeast-2

    skip_cleanup: true
    acl: public_read

    local_dir: deploy
    wait_until_deployed: true
    on:
      repo: seulgiwendy/codesquad-library-v2
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: codesquad-library-backend
    key: deploy/codesquad-library.zip
    bundle_type: zip
    application: codesquad-library
    deployment_group: codesquad-library-backend
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: seulgiwendy/codesquad-library-v2
      branch: master

notifications:
  email:
    recipients:
      - me@wheejuni.com

